### ISSUE TITLE
Release 1.24.8 throws `Unknown provider: tProvider` exception in CrateDB nightly build

### ISSUE THREAD

**Issue by hammerhead** [crate/crate-admin#878]
**Problem**
In CrateDB's latest nightly build, running crate-admin 1.24.8, the Admin UI no longer renders successfully in the browser.

**Steps to reproduce**
Start yesterday's CrateDB night build which ships with crate-admin 1.24.8: `docker run --publish=4200:4200 --publish=5432:5432 --env CRATE_HEAP_SIZE=1g --pull=always --name crate-nightly crate/crate:nightly-5.10.0-2024-11-07-00-02`

Accessing http://localhost:4200 on both Chrome 130 and Firefox 132 shows a blank page together with this error in the JavaScript console:

```
vendor.bundle.js:2 Uncaught Error: [$injector:unpr] Unknown provider: tProvider <- t
https://errors.angularjs.org/1.8.3/$injector/unpr?p0=tProvider%20%3C-%20t
    at vendor.bundle.js:2:68427
    at vendor.bundle.js:2:91245
    at Object.l [as get] (vendor.bundle.js:2:92823)
    at vendor.bundle.js:2:91332
    at l (vendor.bundle.js:2:92823)
    at u (vendor.bundle.js:2:93128)
    at Object.invoke (vendor.bundle.js:2:93216)
    at vendor.bundle.js:2:91512
    at _ (vendor.bundle.js:2:69132)
    at Ze (vendor.bundle.js:2:91490)
```

**Comment by proddata** [comment]
This seems to directly relate to the changes between `1.24.7` -> `1.24.8`

**Comment by msbt** [comment]
Unsure what's happening there, it works fine when building locally, although, now that I'm writing that, I'm also not sure when it's actually using the locally built admin-ui. Because even though the tests work fine, when doing `npm run cratedb` it fetches a docker build which brings its own admin-ui (which until the 29th of October was working). 

So yeah, I can confirm that the nighlies from that day forward are having issues, but I don't know how to debug. Any pointers on how to actually use the local admin-ui and not the one shipped with the cratedb package, what am I missing?

**Comment by proddata** [comment]
>Any pointers on how to actually use the local admin-ui and not the one shipped with the cratedb package, what am I missing?

`npm run develop` 
or `npm run build` and then replace in the cratedb setup (in `lib/site` afaik)

**Comment by kneth** [comment]
I believe I have a ~fix~ workaround in #879
